---
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules.yaml
  - /etc/prometheus/alerts.yaml

scrape_configs:
  - job_name: 'my_node_metrics'
    static_configs:
      - targets:
          - 192.168.66.1:9100
  - job_name: 'my_node_logs'
    static_configs:
      - targets:
          - 192.168.66.1:9144
  - job_name: 'blackbox_http2xx'
    metrics_path: /probe
    params:
      module:
        - http_2xx
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
          - http://faz.net
          - http://bbc.co.uk
          - https://deb.debian.org
          - https://nasa.gov
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.66.1:9115
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['192.168.66.1:9093']
