---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: monitoring
    component: prometheus
  name: monitoring-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-prometheus
    namespace: default
