---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring
    component: prometheus
  name: monitoring-prometheus
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: monitoring
    component: prometheus
  type: "ClusterIP"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring
    component: prometheus
  name: monitoring-prometheus-out
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
      nodePort: 30990
  selector:
    app: monitoring
    component: prometheus
  type: NodePort
