---
# Source: prometheus/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: monitoring
    component: kube-state-metrics
  name: kube-state-metrics
  namespace: default
