apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: monitoring
    component: kube-state-metrics
  name: kube-state-metrics
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: monitoring
    component: kube-state-metrics
  sessionAffinity: None
  type: ClusterIP
