global:
  resolve_timeout: 60m
  slack_api_url: https://webhook.site/<REPLACE>

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 5m

  receiver: operations

receivers:
  - name: 'operations'
    slack_configs:
      - api_url: https://webhook.site/<REPLACE>
        send_resolved: true
