---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: monitoring
    component: nodeexporter
  name: monitoring-nodeexporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: monitoring
      component: nodeexporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monitoring
        component: nodeexporter
    spec:
      serviceAccountName: monitoring-nodeexporter
      containers:
        - name: monitoring-nodeexporter
          args:
            - --path.rootfs=/host
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          image: quay.io/prometheus/node-exporter
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            {}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
