---
# Source: prometheus/templates/node-exporter-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: monitoring
    component: nodeexporter
  name: monitoring-nodeexporter
  namespace: default
